export enum CURRENCIES {
  'AUD' = 'AUD',
  'BGN' = 'BGN',
  'BRL' = 'BRL',
  'CAD' = 'CAD',
  'CHF' = 'CHF',
  'CNY' = 'CNY',
  'CZK' = 'CZK',
  'DKK' = 'DKK',
  'EUR' = 'EUR',
  'GBP' = 'GBP',
  'HKD' = 'HKD',
  'HRK' = 'HRK',
  'HUF' = 'HUF',
  'IDR' = 'IDR',
  'ILS' = 'ILS',
  'INR' = 'INR',
  'ISK' = 'ISK',
  'JPY' = 'JPY',
  'KRW' = 'KRW',
  'MXN' = 'MXN',
  'MYR' = 'MYR',
  'NOK' = 'NOK',
  'NZD' = 'NZD',
  'PHP' = 'PHP',
  'PLN' = 'PLN',
  'RON' = 'RON',
  'RUB' = 'RUB',
  'SEK' = 'SEK',
  'SGD' = 'SGD',
  'THB' = 'THB',
  'TRY' = 'TRY',
  'USD' = 'USD',
  'ZAR' = 'ZAR',
}

export const currencies = [
  { label: '€', value: CURRENCIES.EUR },
  { label: '₽', value: CURRENCIES.RUB },
  { label: '$', value: CURRENCIES.USD },
  { label: '£', value: CURRENCIES.GBP },
  { label: '¥', value: CURRENCIES.JPY },
  { label: '₩', value: CURRENCIES.KRW },
  { label: '₹', value: CURRENCIES.INR },
  { label: 'kr-i', value: CURRENCIES.ISK },
  { label: 'R', value: CURRENCIES.ZAR },
  { label: '₺', value: CURRENCIES.TRY },
  { label: '฿', value: CURRENCIES.THB },
  { label: 'S$', value: CURRENCIES.SGD },
  { label: 'kr-s', value: CURRENCIES.SEK },
  { label: 'lei', value: CURRENCIES.RON },
  { label: 'zł', value: CURRENCIES.PLN },
  { label: '₱', value: CURRENCIES.PHP },
  { label: 'NZ$', value: CURRENCIES.NZD },
  { label: 'kr-n', value: CURRENCIES.NOK },
  { label: 'RM', value: CURRENCIES.MYR },
  { label: 'Mex$', value: CURRENCIES.MXN },
  { label: 'Rp', value: CURRENCIES.IDR },
  { label: '₪', value: CURRENCIES.ILS },
  { label: 'Ft', value: CURRENCIES.HUF },
  { label: 'kn', value: CURRENCIES.HRK },
  { label: 'HK$', value: CURRENCIES.HKD },
  { label: 'kr-d', value: CURRENCIES.DKK },
  { label: 'Kč', value: CURRENCIES.CZK },
  { label: '¥', value: CURRENCIES.CNY },
  { label: '₣', value: CURRENCIES.CHF },
  { label: 'a$', value: CURRENCIES.CAD },
  { label: 'R$', value: CURRENCIES.BRL },
  { label: 'лв', value: CURRENCIES.BGN },
  { label: 'A$', value: CURRENCIES.AUD },
];

export const languageToCurrencyMap: { [key: string]: CURRENCIES } = {
  'en-US': CURRENCIES.USD,
  'en-GB': CURRENCIES.GBP,
  'en-AU': CURRENCIES.AUD,
  'en-CA': CURRENCIES.CAD,
  'en-NZ': CURRENCIES.NZD,
  'en-ZA': CURRENCIES.ZAR,
  'de-DE': CURRENCIES.EUR,
  'fr-FR': CURRENCIES.EUR,
  'es-ES': CURRENCIES.EUR,
  'zh-CN': CURRENCIES.CNY,
  // 'zh-TW': CURRENCIES.TWD,
  'ja-JP': CURRENCIES.JPY,
  'ko-KR': CURRENCIES.KRW,
  'ru-RU': CURRENCIES.RUB,
  'pt-BR': CURRENCIES.BRL,
  'pt-PT': CURRENCIES.EUR,
  'it-IT': CURRENCIES.EUR,
  'nl-NL': CURRENCIES.EUR,
  'sv-SE': CURRENCIES.SEK,
  'no-NO': CURRENCIES.NOK,
  'da-DK': CURRENCIES.DKK,
  'fi-FI': CURRENCIES.EUR,
  'pl-PL': CURRENCIES.PLN,
  'cs-CZ': CURRENCIES.CZK,
  'hu-HU': CURRENCIES.HUF,
  'tr-TR': CURRENCIES.TRY,
  'th-TH': CURRENCIES.THB,
  'id-ID': CURRENCIES.IDR,
  'ms-MY': CURRENCIES.MYR,
  // 'vi-VN': CURRENCIES.VND,
  // 'ar-SA': CURRENCIES.SAR,
  'he-IL': CURRENCIES.ILS,
  'hi-IN': CURRENCIES.INR,
  'el-GR': CURRENCIES.EUR,
  'ro-RO': CURRENCIES.RON,
  'bg-BG': CURRENCIES.BGN,
  'hr-HR': CURRENCIES.HRK,
  'sk-SK': CURRENCIES.EUR,
  'sl-SI': CURRENCIES.EUR,
  'lt-LT': CURRENCIES.EUR,
  'lv-LV': CURRENCIES.EUR,
  'et-EE': CURRENCIES.EUR,
  'mt-MT': CURRENCIES.EUR,
  'is-IS': CURRENCIES.ISK,
  'ga-IE': CURRENCIES.EUR,
  // 'uk-UA': CURRENCIES.UAH,
  // 'sr-RS': CURRENCIES.RSD,
  // 'mk-MK': CURRENCIES.MKD,
  // 'sq-AL': CURRENCIES.ALL,
  // 'bs-BA': CURRENCIES.BAM,
  // 'kk-KZ': CURRENCIES.KZT,
  // 'az-AZ': CURRENCIES.AZN,
  // 'ka-GE': CURRENCIES.GEL,
  // 'hy-AM': CURRENCIES.AMD,
  // 'mn-MN': CURRENCIES.MNT,
  // 'km-KH': CURRENCIES.KHR,
  // 'lo-LA': CURRENCIES.LAK,
  // 'my-MM': CURRENCIES.MMK,
  // 'bn-BD': CURRENCIES.BDT,
  // 'ur-PK': CURRENCIES.PKR,
  'ta-IN': CURRENCIES.INR,
  'te-IN': CURRENCIES.INR,
  'ml-IN': CURRENCIES.INR,
  'kn-IN': CURRENCIES.INR,
  'mr-IN': CURRENCIES.INR,
  'gu-IN': CURRENCIES.INR,
  // 'si-LK': CURRENCIES.LKR,
  // 'ne-NP': CURRENCIES.NPR,
  // 'ps-AF': CURRENCIES.AF,
  // 'am-ET': CURRENCIES.ETB,
  // 'sw-KE': CURRENCIES.KES,
  'zu-ZA': CURRENCIES.ZAR,
  'xh-ZA': CURRENCIES.ZAR,
  'af-ZA': CURRENCIES.ZAR,
};
