export enum CURRENCIES {
  'AUD' = 'AUD',
  'BGN' = 'BGN',
  'BRL' = 'BRL',
  'CAD' = 'CAD',
  'CHF' = 'CHF',
  'CNY' = 'CNY',
  'CZK' = 'CZK',
  'DKK' = 'DKK',
  'EUR' = 'EUR',
  'GBP' = 'GBP',
  'HKD' = 'HKD',
  'HRK' = 'HRK',
  'HUF' = 'HUF',
  'IDR' = 'IDR',
  'ILS' = 'ILS',
  'INR' = 'INR',
  'ISK' = 'ISK',
  'JPY' = 'JPY',
  'KRW' = 'KRW',
  'MXN' = 'MXN',
  'MYR' = 'MYR',
  'NOK' = 'NOK',
  'NZD' = 'NZD',
  'PHP' = 'PHP',
  'PLN' = 'PLN',
  'RON' = 'RON',
  'RUB' = 'RUB',
  'SEK' = 'SEK',
  'SGD' = 'SGD',
  'THB' = 'THB',
  'TRY' = 'TRY',
  'USD' = 'USD',
  'ZAR' = 'ZAR',
}

export const currencies = [
  { label: '€', value: CURRENCIES.EUR },
  { label: '₽', value: CURRENCIES.RUB },
  { label: '$', value: CURRENCIES.USD },
  { label: '£', value: CURRENCIES.GBP },
  { label: '¥', value: CURRENCIES.JPY },
  { label: '₩', value: CURRENCIES.KRW },
  { label: '₹', value: CURRENCIES.INR },
  { label: 'kr-i', value: CURRENCIES.ISK },
  { label: 'R', value: CURRENCIES.ZAR },
  { label: '₺', value: CURRENCIES.TRY },
  { label: '฿', value: CURRENCIES.THB },
  { label: 'S$', value: CURRENCIES.SGD },
  { label: 'kr-s', value: CURRENCIES.SEK },
  { label: 'lei', value: CURRENCIES.RON },
  { label: 'zł', value: CURRENCIES.PLN },
  { label: '₱', value: CURRENCIES.PHP },
  { label: 'NZ$', value: CURRENCIES.NZD },
  { label: 'kr-n', value: CURRENCIES.NOK },
  { label: 'RM', value: CURRENCIES.MYR },
  { label: 'Mex$', value: CURRENCIES.MXN },
  { label: 'Rp', value: CURRENCIES.IDR },
  { label: '₪', value: CURRENCIES.ILS },
  { label: 'Ft', value: CURRENCIES.HUF },
  { label: 'kn', value: CURRENCIES.HRK },
  { label: 'HK$', value: CURRENCIES.HKD },
  { label: 'kr-d', value: CURRENCIES.DKK },
  { label: 'Kč', value: CURRENCIES.CZK },
  { label: '¥', value: CURRENCIES.CNY },
  { label: '₣', value: CURRENCIES.CHF },
  { label: 'a$', value: CURRENCIES.CAD },
  { label: 'R$', value: CURRENCIES.BRL },
  { label: 'лв', value: CURRENCIES.BGN },
  { label: 'A$', value: CURRENCIES.AUD },
];
