name: Production Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  PROJECTS_ROOT: 'itbalis-projects'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build App and Storybook
        run: |
          pnpm build
          pnpm build-storybook

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist
            storybook-static

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Deploy to Production
        run: |
          # Deploy to Vercel
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
          
          echo "🚀 Production deployed" >> $GITHUB_STEP_SUMMARY
          echo "App URL: https://${PROJECTS_ROOT}.vercel.app" >> $GITHUB_STEP_SUMMARY
          echo "Storybook URL: https://${PROJECTS_ROOT}.vercel.app/storybook" >> $GITHUB_STEP_SUMMARY