on:
  pull_request:
    types:
      - opened
      - review_requested

jobs:
  send-tg-message:
      runs-on: ubuntu-latest
      steps:
        - name: Send message to Telegram
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            disable_notification: true
            message: "PR: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}"